
name: Fetch RadioBox Tracks and Generate Top

on:
  schedule:
    - cron: '0 3 * * *'  # Щодня о 03:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install requests beautifulsoup4 pandas

    - name: Run parser
      run: python scripts/parse_tracks.py

    - name: Generate top chart
      run: python scripts/generate_top.py

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add data/tracks.csv data/top.json
        git commit -m "Update tracks and top.json from RadioBox" || echo "No changes to commit"
        git push
