name: Generate & sync paginated tracks log

# Будет срабатывать на пуш, вручную и по расписанию
on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # каждый день в 00:00 UTC

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1) Чекаут
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2) Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3) Скрипт обновления и генерации
      - name: Run update-log script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: node update-log.js

      # 4) Коммит и пуш JSON + все HTML
      - name: Commit and push JSON + HTML pages
        uses: EndBug/add-and-commit@v9
        with:
          author_name:  'github-actions[bot]'
          author_email: 'github-actions[bot]@users.noreply.github.com'
          message:      'chore: sync and regenerate tracks log'
          add: |
            tracks-log.json
            tracks-log.html
            tracks-log-page*.html
          push: true
