name: Sync Supabase → paginated tracks log

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # ежедневно в 00:00 UTC

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Run update-log script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: node update-log.js

      - name: Commit and push JSON + HTML pages
        uses: EndBug/add-and-commit@v9
        with:
          author_name:  'github-actions[bot]'
          author_email: 'github-actions[bot]@users.noreply.github.com'
          message:      'chore: sync and regenerate tracks log'
          add:          'tracks-log.json,tracks-log.html,tracks-log-page*.html'
          push:         true
